kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-database
  namespace: RM340569
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
