apiVersion: kustomize.config.k8s.io/v1beta1
kind: lab-provider
namespace: RM340569
resources:
  - deployment/blog.deployment.yml
  - deployment-config/sample-database.deploymentconfig.yml
  - hpa/hpa.yml
  - pvc/sample-database.pvc.yml
  - secret/blog.secret.yml
  - secret/sample-database.secret.yml
  - service/blog.service.yml
  - service/sample-database.service.yml
  - route/blog.route.yml