kind: Service
apiVersion: v1
metadata:
  name: sample-database-service
  namespace: rm340569
  labels:
    app: sample-database-service
spec:
  ports:
    - protocol: TCP
      port: 5432
  selector:
    name: sample-database
  type: LoadBalancer